#!/bin/bash
#PBS -l nodes=1:ppn=12
#PBS -l walltime=00:30:00
#PBS -q batch
#PBS -N serial
#PBS -j oe

cd /home/rawsonb/final/serial
for i in `seq 10000000 10000000 100000000`; do
    ./sort.cx $i 0 10000
done