#!/bin/bash
#PBS -l nodes=1:ppn=12
#PBS -l walltime=00:30:00
#PBS -q batch
#PBS -N openmp
#PBS -j oe

cd /home/rawsonb/final/openmp
for i in `seq 1 12`; do
    export OMP_NUM_THREADS=$i
    ./sort.cx 40000000 0 10000
done